//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/BouncingBallInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BouncingBallInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BouncingBallInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BouncingBallInputActions"",
    ""maps"": [
        {
            ""name"": ""Bouncing Ball"",
            ""id"": ""2233a633-1739-4df2-9bd0-75a78f9fad77"",
            ""actions"": [
                {
                    ""name"": ""Bounce"",
                    ""type"": ""Button"",
                    ""id"": ""9713c64f-9c2a-4ed1-827d-50bd9da308b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=1,pressPoint=0.001)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""43c0eb8e-56da-437b-96b4-3fcd7c946362"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bounce"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Bouncing Ball
        m_BouncingBall = asset.FindActionMap("Bouncing Ball", throwIfNotFound: true);
        m_BouncingBall_Bounce = m_BouncingBall.FindAction("Bounce", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Bouncing Ball
    private readonly InputActionMap m_BouncingBall;
    private IBouncingBallActions m_BouncingBallActionsCallbackInterface;
    private readonly InputAction m_BouncingBall_Bounce;
    public struct BouncingBallActions
    {
        private @BouncingBallInputActions m_Wrapper;
        public BouncingBallActions(@BouncingBallInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Bounce => m_Wrapper.m_BouncingBall_Bounce;
        public InputActionMap Get() { return m_Wrapper.m_BouncingBall; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BouncingBallActions set) { return set.Get(); }
        public void SetCallbacks(IBouncingBallActions instance)
        {
            if (m_Wrapper.m_BouncingBallActionsCallbackInterface != null)
            {
                @Bounce.started -= m_Wrapper.m_BouncingBallActionsCallbackInterface.OnBounce;
                @Bounce.performed -= m_Wrapper.m_BouncingBallActionsCallbackInterface.OnBounce;
                @Bounce.canceled -= m_Wrapper.m_BouncingBallActionsCallbackInterface.OnBounce;
            }
            m_Wrapper.m_BouncingBallActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Bounce.started += instance.OnBounce;
                @Bounce.performed += instance.OnBounce;
                @Bounce.canceled += instance.OnBounce;
            }
        }
    }
    public BouncingBallActions @BouncingBall => new BouncingBallActions(this);
    public interface IBouncingBallActions
    {
        void OnBounce(InputAction.CallbackContext context);
    }
}
